// tinies — Generated by Refine Design (refinedesign.ai)
// Paste into tailwind.config.ts → theme.extend

import type { Config } from 'tailwindcss';

const config: Config = {
  "theme": {
    "extend": {
      "colors": {
        "primary": {
          "50": "#F1F9F9",
          "100": "#DFF6F6",
          "200": "#B3F9F9",
          "300": "#7BF5F5",
          "400": "#38EFEF",
          "500": "#11DADA",
          "600": "#0DAAAA",
          "700": "#0A8484",
          "800": "#075F5F",
          "900": "#064141",
          "950": "#072222"
        },
        "secondary": {
          "50": "#F9F1F0",
          "100": "#F7E1DE",
          "200": "#FABBB2",
          "300": "#F78878",
          "400": "#F34C35",
          "500": "#DD270D",
          "600": "#AD1E0A",
          "700": "#871808",
          "800": "#601106",
          "900": "#420D05",
          "950": "#220A07"
        },
        "accent": {
          "50": "#F1F9F9",
          "100": "#DFF6F6",
          "200": "#B3F9F9",
          "300": "#7BF5F5",
          "400": "#38EFEF",
          "500": "#11DADA",
          "600": "#0DAAAA",
          "700": "#0A8484",
          "800": "#075F5F",
          "900": "#064141",
          "950": "#072222"
        },
        "background": "#FFFFFF",
        "text-primary": "#1C1C1C",
        "neutral": {
          "50": "#F5F5F5",
          "100": "#EBEBEB",
          "200": "#D6D6D6",
          "300": "#B8B8B8",
          "400": "#949494",
          "500": "#757575",
          "600": "#5C5C5C",
          "700": "#474747",
          "800": "#333333",
          "900": "#242424",
          "950": "#141414"
        }
      },
      "fontFamily": {
        "heading": [
          "GCentra",
          "serif"
        ],
        "body": [
          "Roboto",
          "sans-serif"
        ]
      },
      "borderRadius": {
        "sm": "4px",
        "md": "8px",
        "lg": "12px",
        "xl": "16px"
      }
    }
  }
};

export default config;
